sudo: required
services: 
  - docker

before_install: 
  - docker build -t sanchitverma/docker-react -f Dockerfile.dev .

script:
  - docker run sanchitverma/docker-react npm run test -- --watchAll=False
